services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: clinica-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: clinica
      POSTGRES_PASSWORD: clinica_dev
      POSTGRES_DB: clinica_rag

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: